<?php

    $config = array(
				'db_hostname' => 'localhost',
				'db_uname' => 'ppm_2020',
				'db_passwd' => '',
				'dbname' => 'ppm_2020'
		  );
		 
    global $con;
    
    $con = mysqli_connect($config['db_hostname'], $config['db_uname'], $config['db_passwd']);
    
    if(!$con){
        die(trigger_error("Connection failed : ".mysqli_connect_error()));
    }else{
        mysqli_select_db($con, $config['dbname']);
    }
    
    $array_mhs_bea = array("ABDUL AZIZ", "ADELIA SELLI UTAMI", "AFNI ROHMAWATI LUTFIA", "AGISTA PANGESTU", "ALDI ARTHA MIDA", "ALIFIA NUROHMAH", "ANGGIE NURSHAFIRA", "ANGGIT ALDO ARYADIKA", "ANINDITA SEPTI DAIMA ULFA", "BAGUS DUANE CAHYO PURNOMO", "CHELCIA BABY ANGGRAYNI", "DEGA ANJAM PIANI", "DWI CAHYO SEPTYA SRIHANDOKO", "DWI NUGRAHENI", "DZIRA FAUZIYYAH", "ELSARI AJENG PUTRI", "ERFILA JULIA DAMAYANTI", "ERIKA OKTAVIANA", "ERWIN RAHARDIAN PUTRA", "EUNIKE ANGELLITA WISNU MAHARANI", "FANIA JULIANTI CAHYANINGRUM", "FERIENA JANUVIKA DWI SARASWATI", "FIRMANSYAH ARDHANI PUTRA", "GALANG ADHITYA RAMADHAN", "GALENT MARGAREZA GUSSIWI", "HAFIVAH ISNUR ETIKA PUTRI", "HUMAIMAH MAIMUN FITRI SALSABILA", "IKHWAN NUR ALIF WIDIYANTO", "LAILA NUR ROHMAH", "LATIVA DHURRATUN HIKMAWATI", "LILIANA ISTIKOMAH", "LUTHFIATUN NAMIIROTUL JANNAH", "MAYLAF FASYA", "MEYSZAROH PUTRI SULISTYA RINI", "MUHAMMAD RIYADL HUSNUL MUBAROK", "NABILA APRILIA PUTRI", "NADIA NUR`AINI WIDYANINGRUM", "NAUFAL FEBRIAN", "NINDA PUTRI AISWARA", "NISRINA AL HUSNA PUTRI", "NOVI ANGGRAENI", "NURUS SHOFIATUL A", "PUTRI NURLITA SARI", "REKYAN LAKHSITA DEWATI", "RIDHO FAHRUROZI", "RIRIN MUTHII`ATUSSOLIKHAH", "RISANG KILAT BHAWANA DJATI", "RISNA NUR AZIZAH", "RIZQI NUGROHO", "ROCHIMA NURAINI", "ROJAB PANJALU", "RONI SETIAWAN", "SALMA ABDUL SHOBARUN", "SALMA TIRTA", "SISKA MELIASARI", "TANTI EKA YULIANA", "WAHYU DHARMA KUSUMA", "WINDA HERMASTUTI", "WIWIT DWI RAHMAWATI", "YUSRON RAFI` LUKMANUL HAKIM", "AHMAD IRFANSYAH", "AHMAD ISNAN WAHYUDI", "AKBAR DWI APRIANTORO", "AKBAR NUR GILBRANT", "ALEK DESTA KRISTANTO", "ALYA RENDHRIVA SAPUTRI", "AMALIA PUSPITANINGRUM", "ANGGIT DWI NURASFAN", "ASTRI WAHYU LESTARI", "BAYU SATRIA NUGROHO", "BOBY RANGGA DANUARTHA", "DAFA AYMAN ZULFIKAR", "DAFANSYAH JUAN FABIO", "DAFFA' IKHSANUL FIKRI", "DESI OKSIANA SETYAWATI", "DEVI NUR ANISAH", "DHIO LINTANG MARTINO", "DIKI ARYA PRATAMA", "EKA HAFSAH MARDIARSO", "ERVINA RISZAN RAMADHAN", "FAREL RADITYA ROIKHUL HERMAWAN", "FARID EKA PRATAMA", "FAWWAZ NUR HAKIM", "GALIH DWI MULIANTO", "GHEANIDA AIS PUTRI AZIZIAH", "GHISKA ARNA RAMADANI", "HELINA BUDIARTI DWI ASTUTI", "HENDY PREVIDIANSYAH", "IBNU AHMADALLATIF WICAKSONO", "IBNU RESTU WIJAYA", "ILHAM WAHYUDI", "INDI KHOIRUNNISA", "INDRA ARDIANSYAH", "IRFAN HAKIM", "ISWARA PUTRI JILAN TSABITA", "M RIDWAN NURDIYANTO", "M. FARREL GHAISAN", "MEISYA QEENA SHEEHAN RUSMIYANTO", "MOHAMMAD FURQON PUTRA CHOIR", "MUHAMAD DENI NUR FAUZAN", "MUHAMMAD ATHA NAFI`", "MUHAMMAD FAISHAL THOFA RAFIF", "MUHAMMAD IKHWANUL HIDAYAH", "MUHAMMAD NU`MAN FARID YAZID", "MUHAMMAD RAKHA NAYOTAMA RIMAWAN", "MUHAMMAD WILDAN ZHALIFUNAS", "NAJWA AULIA NOVIANA", "RESTU NEVIA IRIANTI", "RIDWAN DWI KURNIAWAN", "RIFKY RAMADANI", "RIVALDO PUTRA RICHSENSA", "RIYANRIDHOALFADILA", "SALSA BILLA AURILIA", "SANJENAR RAIHAN HARYO PANTUN", "SETYA ANDI WARDANA", "SHAFA AFRIEZA PUTERI", "TIKO AHMAD SYAFARUDIN", "VERANI SHEIRA AZIZAH", "WAHYU FATIATIS SHOLIKHAH", "YOGA ANGGA PRATAMA", "ADITYA HAFIS AL ISLAMI", "DAVA AGUS SETIAWAN", "DIANDRA RIFKY HARDIKA", "NUR MUHAMMAD FERDYAN", "TYASNO SAMBUDI", "FAJRI AULIA WULANSARI", "AVIVAH NADIA WULANDARI", "FARHAN AHMAD SETIAWAN", "DESVITA MELANI", "HAYATUNNISA ARUM HANDAYANI", "VITA NURUL INAYAH");
    
    $no = 0;
    foreach($array_mhs_bea as $key => $value) {
        
        $sql = "SELECT mahasiswa.npm,mahasiswa.no_tes,potensi.id_potensi FROM mahasiswa LEFT JOIN potensi ON potensi.npm = mahasiswa.npm where mahasiswa.id_thn = 17 and mahasiswa.nama = '".$value."'";
        $result = $con->query($sql);
        
        
        if (mysqli_num_rows($result) > 0) {
             $no++;
          // output data of each row
          while($row = mysqli_fetch_assoc($result)) {
             
            echo ($no).". Nama : ".$value." Sudah punya NPM : ".$row['npm'].", No. tes : ".$row['no_tes'].", ID Potensi : ".$row['id_potensi']."<br>";
          }
        }
    }
    
    
    
    
    
